swagger: "2.0"
info:
  title: Feeta api
  version: 1.0
  contact:
    email: sidhant@thelattice.in
  server:
    url: "http://localhost:5000"
    description: "DEVELOPMENT SERVER"
    url: "http://157.245.100.190"
    description: "PRODUCTION SERVER"

schemes: [http, https]

# securityDefinitions:
  # BasicAuth:
  #   type: basic
  # JWT:
  #   description:
  #   type: apiKey
  #   name: Authorization
  #   in: header

host: localhost:5000
basePath: /api
paths:
  
  /register-snapshot: 
    post:
      summary: create snapshot
      produces:
        - application/json
      consumes:
        - application/json
      parameters: 
        - in: body
          name: snapshot
          schema:
            type: object
            properties:
              snapshot_date: 
                type: string
              snapshot_url:
                type: string
              
        
      responses:
        201:
          description: project snapshot created
          schema:
            type: object
            properties: 
              status: 
                type: integer
              project_id:
                type: string
              snapshot_date:
                type: string
              snapshot_url:
                type: string
              message:
                type: string

        400:
          description: validation error
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
        500:
          description: Internal server error
          schema:
            type: object
            properties: 
              status: 
                type: integer
              message:
                type: string
  /add-note: 
    post:
      summary: add notes
      produces:
        - application/json
      consumes:
        - application/json
      parameters: 
        - in: body
          name: notes
          schema:
            type: object
            properties:
              project_id:
                type: string
              note: 
                type: string
              
              
        
      responses:
        201:
          description: project snapshot created
          schema:
            type: object
            properties: 
              status: 
                type: integer
              message:
                type: string

        400:
          description: validation error
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
        500:
          description: Internal server error
          schema:
            type: object
            properties: 
              status: 
                type: integer
              message:
                type: string
  /get-notes/{id}:
    get:
      summary: return project notes
      # description: This provides various details about the hospital like patient and psychologist details in particular hospital. Use hospitalid as 3 for testing purpose
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The project id whos details are needed to be fetched 
      responses:
        200:
          description: notes
          schema: 
            type: object
            properties:
              status:
                type: integer
              notes:
                type: array
                items: 
                  type: object
                  properties: 
                    project_id:
                      type: string
                    note:
                      type: string
                    date_created: 
                      type: string
        400:
          description: Bad request. project id required
          schema:
            type: object
            properties: 
              status: 
                type: integer
              message:
                type: string
        500:
          description: Internal server error
          schema:
            type: object
            properties: 
              status: 
                type: integer
              message:
                type: string
  /project-summary/{id}:
    get:
      summary: return project summary
      description: This provides various details about project
      parameters:
        - in: path
          name: projectID
          schema:
            type: integer
          required: true
          description: project details
      responses:
        200:
          schema:
            type: object
            properties:
              total_progress:
                type: integer
              time_elapsed:
                type: integer
              buffer_used: 
                type: integer
              gantt_snapshot_url:
                type: string
              date_of_snapshot:
                type: string
              project_id:
                type: string
              expected_end:
                type: object
                properties:
                  days_left: 
                    type: integer
                  end_date:
                    type: string
              del_goaEnd:
                type: integer
              del_nextMilestone:
                type: integer
              del_bufferLastWeek:
                type: integer
              del_totRework:
                type: integer
              del_reworkLastWeek:
                type: integer
              milestone_tasks:
                type: array
                items: 
                  type: object
                  properties: 
                    id:
                      type: number
                    name:
                      type: string
                    deadline: 
                      type: string
                    delayed_status:
                      type: string
              delayed_tasks:
                type: array
                items: 
                  type: object
                  properties: 
                    id:
                      type: number
                    delay_days:
                      type: string
                    task_name: 
                      type: string
                    deadline:
                      type: string
                    assigned_to:
                      typee: array
        404:
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
        500:
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string



                      